version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: analyst
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: etl
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'

  dashboard:
    build: .
    restart: always
    depends_on:
      - postgres
    ports:
      - "8503:8503"
    volumes:
      - .:/app   # 🔥 ВОТ ЭТО КЛЮЧЕВОЕ
    command: streamlit run dashboard/app.py --server.port=8503 --server.address=0.0.0.0

volumes:
  pg_data:
